# Generated by Django 4.2.14 on 2024-08-25 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradingJournal',
            new_name='TradeJournal',
        ),
    ]
