# Generated by Django 4.2.14 on 2024-08-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_journal', '0002_rename_tradingjournal_tradejournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradejournal',
            name='currency',
            field=models.CharField(default='', max_length=20, verbose_name='거래소'),
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='symbol',
            field=models.CharField(default='', max_length=20, verbose_name='심볼'),
        ),
    ]
